_current_progress_remaining:
    value: 1
_custom_logger:
    value: "False"
_episode_num:
    value: 0
_last_episode_starts:
    value: '[ True  True]'
_last_obs:
    value: |-
        [[[[  0   0   0 ...   0   0   0]
           [  0   0   0 ...   0   0   0]
           [  0   0   0 ...   0   0   0]
           ...
           [  0   0   0 ...   0   0   0]
           [  0   0   0 ...   0   0   0]
           [  0   0   0 ...   0   0   0]]

          [[  0   0   0 ...   0   0   0]
           [  0   0   0 ...   0   0   0]
           [  0   0   0 ...   0   0   0]
           ...
           [  0   0   0 ...   0   0   0]
           [  0   0   0 ...   0   0   0]
           [  0   0   0 ...   0   0   0]]

          [[  0   0   0 ...   0   0   0]
           [  0   0   0 ...   0   0   0]
           [  0   0   0 ...   0   0   0]
           ...
           [  0   0   0 ...   0   0   0]
           [  0   0   0 ...   0   0   0]
           [  0   0   0 ...   0   0   0]]

          [[ 17  17  17 ...  17  17  17]
           [ 17  17  17 ...  17  17  17]
           [ 17  17  17 ...  17  17  17]
           ...
           [236 236 236 ... 236 236 236]
           [236 236 236 ... 236 236 236]
           [236 236 236 ... 236 236 236]]]


         [[[  0   0   0 ...   0   0   0]
           [  0   0   0 ...   0   0   0]
           [  0   0   0 ...   0   0   0]
           ...
           [  0   0   0 ...   0   0   0]
           [  0   0   0 ...   0   0   0]
           [  0   0   0 ...   0   0   0]]

          [[  0   0   0 ...   0   0   0]
           [  0   0   0 ...   0   0   0]
           [  0   0   0 ...   0   0   0]
           ...
           [  0   0   0 ...   0   0   0]
           [  0   0   0 ...   0   0   0]
           [  0   0   0 ...   0   0   0]]

          [[  0   0   0 ...   0   0   0]
           [  0   0   0 ...   0   0   0]
           [  0   0   0 ...   0   0   0]
           ...
           [  0   0   0 ...   0   0   0]
           [  0   0   0 ...   0   0   0]
           [  0   0   0 ...   0   0   0]]

          [[ 17  17  17 ...  17  17  17]
           [ 17  17  17 ...  17  17  17]
           [ 17  17  17 ...  17  17  17]
           ...
           [236 236 236 ... 236 236 236]
           [236 236 236 ... 236 236 236]
           [236 236 236 ... 236 236 236]]]]
_last_original_obs:
    value: None
_logger:
    value: <stable_baselines3.common.logger.Logger object at 0x713926c83ad0>
_n_updates:
    value: 0
_num_timesteps_at_start:
    value: 0
_stats_window_size:
    value: 100
_total_timesteps:
    value: 2000000
_vec_normalize_env:
    value: None
_wandb:
    value:
        cli_version: 0.19.0
        code_path: code/src/sb3_pong.py
        m: []
        python_version: 3.11.14
        t:
            "1":
                - 1
                - 55
            "2":
                - 1
                - 55
            "3":
                - 13
                - 16
                - 22
                - 23
                - 35
                - 55
            "4": 3.11.14
            "5": 0.19.0
            "8":
                - 5
            "12": 0.19.0
            "13": linux-x86_64
action_noise:
    value: None
action_space:
    value: Discrete(6)
algo:
    value: PPO
batch_size:
    value: 64
clip_range:
    value: <function get_schedule_fn.<locals>.<lambda> at 0x71394c53ac00>
clip_range_vf:
    value: None
device:
    value: cuda
ent_coef:
    value: 0
env:
    value:
        export_path: ./models/
        policy_type: CnnPolicy
        total_timesteps: 2000000
ep_info_buffer:
    value: deque([], maxlen=100)
ep_success_buffer:
    value: deque([], maxlen=100)
gae_lambda:
    value: 0.95
gamma:
    value: 0.99
learning_rate:
    value: 0.0003
lr_schedule:
    value: <function get_schedule_fn.<locals>.<lambda> at 0x71394c539760>
max_grad_norm:
    value: 0.5
n_envs:
    value: 2
n_epochs:
    value: 10
n_steps:
    value: 2048
normalize_advantage:
    value: "True"
num_timesteps:
    value: 0
observation_space:
    value: Box(0, 255, (4, 84, 84), uint8)
policy:
    value: |-
        ActorCriticCnnPolicy(
          (features_extractor): NatureCNN(
            (cnn): Sequential(
              (0): Conv2d(4, 32, kernel_size=(8, 8), stride=(4, 4))
              (1): ReLU()
              (2): Conv2d(32, 64, kernel_size=(4, 4), stride=(2, 2))
              (3): ReLU()
              (4): Conv2d(64, 64, kernel_size=(3, 3), stride=(1, 1))
              (5): ReLU()
              (6): Flatten(start_dim=1, end_dim=-1)
            )
            (linear): Sequential(
              (0): Linear(in_features=3136, out_features=512, bias=True)
              (1): ReLU()
            )
          )
          (pi_features_extractor): NatureCNN(
            (cnn): Sequential(
              (0): Conv2d(4, 32, kernel_size=(8, 8), stride=(4, 4))
              (1): ReLU()
              (2): Conv2d(32, 64, kernel_size=(4, 4), stride=(2, 2))
              (3): ReLU()
              (4): Conv2d(64, 64, kernel_size=(3, 3), stride=(1, 1))
              (5): ReLU()
              (6): Flatten(start_dim=1, end_dim=-1)
            )
            (linear): Sequential(
              (0): Linear(in_features=3136, out_features=512, bias=True)
              (1): ReLU()
            )
          )
          (vf_features_extractor): NatureCNN(
            (cnn): Sequential(
              (0): Conv2d(4, 32, kernel_size=(8, 8), stride=(4, 4))
              (1): ReLU()
              (2): Conv2d(32, 64, kernel_size=(4, 4), stride=(2, 2))
              (3): ReLU()
              (4): Conv2d(64, 64, kernel_size=(3, 3), stride=(1, 1))
              (5): ReLU()
              (6): Flatten(start_dim=1, end_dim=-1)
            )
            (linear): Sequential(
              (0): Linear(in_features=3136, out_features=512, bias=True)
              (1): ReLU()
            )
          )
          (mlp_extractor): MlpExtractor(
            (policy_net): Sequential()
            (value_net): Sequential()
          )
          (action_net): Linear(in_features=512, out_features=6, bias=True)
          (value_net): Linear(in_features=512, out_features=1, bias=True)
        )
policy_class:
    value: <class 'stable_baselines3.common.policies.ActorCriticCnnPolicy'>
policy_kwargs:
    value: '{}'
rollout_buffer:
    value: <stable_baselines3.common.buffers.RolloutBuffer object at 0x7139538a4c50>
rollout_buffer_class:
    value: <class 'stable_baselines3.common.buffers.RolloutBuffer'>
rollout_buffer_kwargs:
    value: '{}'
sde_sample_freq:
    value: -1
seed:
    value: None
start_time:
    value: 1764419165697316455
target_kl:
    value: None
tensorboard_log:
    value: runs/qild3rbr
use_sde:
    value: "False"
verbose:
    value: 0
vf_coef:
    value: 0.5
