_current_progress_remaining:
    value: 1
_custom_logger:
    value: "False"
_episode_num:
    value: 0
_last_episode_starts:
    value: '[ True]'
_last_obs:
    value: |-
        [[[[ 52  52  52 ...  87  87  87]
           [ 87  87  87 ...  87  87  87]
           [ 87  87  87 ...  87  87  87]
           ...
           [236 236 236 ... 236 236 236]
           [236 236 236 ... 236 236 236]
           [236 236 236 ... 236 236 236]]

          [[ 52  52  52 ...  87  87  87]
           [ 87  87  87 ...  87  87  87]
           [ 87  87  87 ...  87  87  87]
           ...
           [236 236 236 ... 236 236 236]
           [236 236 236 ... 236 236 236]
           [236 236 236 ... 236 236 236]]

          [[ 52  52  52 ...  87  87  87]
           [ 87  87  87 ...  87  87  87]
           [ 87  87  87 ...  87  87  87]
           ...
           [236 236 236 ... 236 236 236]
           [236 236 236 ... 236 236 236]
           [236 236 236 ... 236 236 236]]

          [[ 52  52  52 ...  87  87  87]
           [ 87  87  87 ...  87  87  87]
           [ 87  87  87 ...  87  87  87]
           ...
           [236 236 236 ... 236 236 236]
           [236 236 236 ... 236 236 236]
           [236 236 236 ... 236 236 236]]]]
_last_original_obs:
    value: None
_logger:
    value: <stable_baselines3.common.logger.Logger object at 0x72bf346106d0>
_n_updates:
    value: 0
_num_timesteps_at_start:
    value: 0
_stats_window_size:
    value: 100
_total_timesteps:
    value: 1000000
_vec_normalize_env:
    value: None
_wandb:
    value:
        cli_version: 0.19.0
        m: []
        python_version: 3.11.14
        t:
            "1":
                - 1
                - 55
                - 105
            "2":
                - 1
                - 55
                - 105
            "3":
                - 13
                - 16
                - 22
                - 23
                - 35
                - 55
            "4": 3.11.14
            "5": 0.19.0
            "8":
                - 5
            "12": 0.19.0
            "13": linux-x86_64
action_noise:
    value: None
action_space:
    value: Discrete(6)
algo:
    value: PPO
batch_size:
    value: 32
clip_range:
    value: <function get_schedule_fn.<locals>.<lambda> at 0x72bf4cffb6a0>
clip_range_vf:
    value: None
device:
    value: cuda
ent_coef:
    value: 0.01
env:
    value: <stable_baselines3.common.vec_env.vec_video_recorder.VecVideoRecorder object at 0x72bf582022d0>
env_id:
    value: PongNoFrameskip-v4
ep_info_buffer:
    value: deque([], maxlen=100)
ep_success_buffer:
    value: deque([], maxlen=100)
export_path:
    value: ./models/
gae_lambda:
    value: 0.95
gamma:
    value: 0.99
learning_rate:
    value: 0.0001
lr_schedule:
    value: <function get_schedule_fn.<locals>.<lambda> at 0x72bf4cff9800>
max_grad_norm:
    value: 0.5
model_name:
    value: ppo_pong_standard
n_envs:
    value: 1
n_epochs:
    value: 4
n_steps:
    value: 128
normalize_advantage:
    value: "True"
num_timesteps:
    value: 0
observation_space:
    value: Box(0, 255, (4, 84, 84), uint8)
policy:
    value: |-
        ActorCriticCnnPolicy(
          (features_extractor): NatureCNN(
            (cnn): Sequential(
              (0): Conv2d(4, 32, kernel_size=(8, 8), stride=(4, 4))
              (1): ReLU()
              (2): Conv2d(32, 64, kernel_size=(4, 4), stride=(2, 2))
              (3): ReLU()
              (4): Conv2d(64, 64, kernel_size=(3, 3), stride=(1, 1))
              (5): ReLU()
              (6): Flatten(start_dim=1, end_dim=-1)
            )
            (linear): Sequential(
              (0): Linear(in_features=3136, out_features=512, bias=True)
              (1): ReLU()
            )
          )
          (pi_features_extractor): NatureCNN(
            (cnn): Sequential(
              (0): Conv2d(4, 32, kernel_size=(8, 8), stride=(4, 4))
              (1): ReLU()
              (2): Conv2d(32, 64, kernel_size=(4, 4), stride=(2, 2))
              (3): ReLU()
              (4): Conv2d(64, 64, kernel_size=(3, 3), stride=(1, 1))
              (5): ReLU()
              (6): Flatten(start_dim=1, end_dim=-1)
            )
            (linear): Sequential(
              (0): Linear(in_features=3136, out_features=512, bias=True)
              (1): ReLU()
            )
          )
          (vf_features_extractor): NatureCNN(
            (cnn): Sequential(
              (0): Conv2d(4, 32, kernel_size=(8, 8), stride=(4, 4))
              (1): ReLU()
              (2): Conv2d(32, 64, kernel_size=(4, 4), stride=(2, 2))
              (3): ReLU()
              (4): Conv2d(64, 64, kernel_size=(3, 3), stride=(1, 1))
              (5): ReLU()
              (6): Flatten(start_dim=1, end_dim=-1)
            )
            (linear): Sequential(
              (0): Linear(in_features=3136, out_features=512, bias=True)
              (1): ReLU()
            )
          )
          (mlp_extractor): MlpExtractor(
            (policy_net): Sequential()
            (value_net): Sequential()
          )
          (action_net): Linear(in_features=512, out_features=6, bias=True)
          (value_net): Linear(in_features=512, out_features=1, bias=True)
        )
policy_class:
    value: <class 'stable_baselines3.common.policies.ActorCriticCnnPolicy'>
policy_kwargs:
    value: '{}'
project_name:
    value: Step2-RLProject
rollout_buffer:
    value: <stable_baselines3.common.buffers.RolloutBuffer object at 0x72bf51950c90>
rollout_buffer_class:
    value: <class 'stable_baselines3.common.buffers.RolloutBuffer'>
rollout_buffer_kwargs:
    value: '{}'
sde_sample_freq:
    value: -1
seed:
    value: None
start_time:
    value: 1764429003060517208
target_kl:
    value: None
tensorboard_log:
    value: runs/80gwhufc
total_timesteps:
    value: 1000000
use_sde:
    value: "False"
verbose:
    value: 1
vf_coef:
    value: 0.5
