_wandb:
    value:
        cli_version: 0.19.0
        code_path: code/src/sb3_pong.py
        m: []
        python_version: 3.11.14
        t:
            "1":
                - 1
                - 55
            "2":
                - 1
                - 55
            "3":
                - 13
                - 16
                - 22
                - 23
                - 35
                - 55
            "4": 3.11.14
            "5": 0.19.0
            "8":
                - 5
            "12": 0.19.0
            "13": linux-x86_64
env:
    value:
        export_path: ./models/
        policy_type: CnnPolicy
        total_timesteps: 2000000
